spring:
  application:
    name: library-worker-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true #true by default
    register-with-eureka: true #true by default
    service-url:
      defaultZone: http://localhost:8761/eureka